# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HeyPlay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for HeyPlay
  pod "HockeySDK", :subspecs => ['AllFeaturesLib']

  target 'HeyPlayTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
